### PR TITLE
[TS] LPS-102763 LDAP password gets overridden if the login fails for the first time

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-102763](https://issues.liferay.com/browse/LPS-102763)

Hi Norbi,

Thanks again for discussing the issue yesterday. I hope you can review my changes. 

**Issue recap:** When first user login fails, the user still gets imported with an autogenerated password which unfortunately get exported back to LDAP.

**Solution:** My understanding is that exporting the password to LDAP during the authentication doesn't make sense. In case of user password change is required, it happens after the authentication. My changes ensures than no password export happens during the authentication. 

Please let me know if you have any concerns.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:ldap

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
Hi @NorbertKocsis ,

I have fixed the SF failure. 

There is a functional test failure that may be related, however I would say it isn't. Can we talk about it tomorrow?

Thank you,
Pisti

**Comment by istvansajtos** [comment]
ci:test:ldap

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
Thanks! Forwarded to https://github.com/stian-sigvartsen/liferay-portal/pull/208

**Pull request closed without merging**
