### PR TITLE
LPS-98301 Internal Server Error thrown due to orphan portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-98301](https://issues.liferay.com/browse/LPS-98301).<br><br>Hey Norbert, can you please take another look at this solution per Brian's comment here? https://github.com/brianchandotcom/liferay-portal/pull/80324#issuecomment-548497524 

Thanks! Let me know if you need my help with anything.

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
Hi,

I'm a bit confused about this. I was following the pattern in cleanUpLayoutRevisionPortletPreferences().

Br,
Norbert

**Comment by drewbrokke** [comment]
Hey @NorbertKocsis,

I think this pull drew Brian's attention to the pattern, and he decided it was incorrect. He may be expecting us to cache the current value of `active` from `CacheRegistryUtil` (similar to how it's done with `ThreadLocal` classes). From what I understand, `CacheRegistryUtil` is intended to be used inside upgrades and not during normal server usage since there could be side-effects from clearing all the caches.

I'd say at the very least, do a `ThreadLocal`-style cache of the current value of `active` (and perhaps apply to the other case that you copied).

**Comment by NorbertKocsis** [comment]
Synchronizing doesn't seem neccessary as CacheRegistryUtil.setActive() is only used by the upgrade, verify and these two server admin tasks (and some integration tests). And not using and clearing the caches once during a maintenance task is not something which I would consider a problem.

**Comment by NorbertKocsis** [comment]
Hi,

Did you have a chance to read my last comment?

Br,
Norbert

**Comment by NorbertKocsis** [comment]
Hi @drewbrokke !

Could you please check out my last comment?

Br,
Norbert

**Comment by drewbrokke** [comment]
Hey @NorbertKocsis sorry about the delay on this. Your explanations make sense. I'll re-send to Brian with a link to your comments. If he has any other issues I'll speak with him.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81068

**Pull request closed without merging**
