### PR TITLE
[TS] LPS-70266 Prevent any content management on Control Panel site

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Norbi,

This fix prevents content management attempts on Control Panel site, which was possible through URL rewriting. 

I have implemented the solution in FriendlyURLServlet, because it is where URLs are parsed and necessary checks can be implemented easily.

We talked a little bit about this on Friday. Please let me know if you have any concerns or observations.

Thanks,
Pisti

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
Hi Pisti,

Could you please double check this? I can still reproduce the issue.

Br,
Norbert

**Comment by istvansajtos** [comment]
Hi Norbi,

You are right! I forgot to commit my latest changes, this way PortalUtil#isControlPanelPortlet was not parametrized well. I'm so sorry for that.

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Closing and resending to see if it eliminates Poshi errors.

**Pull request closed without merging**
