### PR TITLE
LPS-80444 During the db upgrade process a few warning appear related to Kaleo

### PR DESCRIPTION
**Pull request by amadeafejes**
https://issues.liferay.com/browse/LPS-80444

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test

**Comment by NorbertKocsis** [comment]
Hi,

It seems to be ok but please take it apart per entities as we do elsewhere! Could you do that and resend?

Br,
Norbert

**Comment by amadeafejes** [comment]
Hi @NorbertKocsis 

I have just updated my branch with the modifications you suggested.
Could you please check it?

Thanks

**Comment by amadeafejes** [comment]
ci:retest

**Comment by NorbertKocsis** [comment]
Thanks!
Forwarded to https://github.com/jeyvison/liferay-portal/pull/61

**Pull request closed without merging**
