### PR TITLE
[TECHNICAL-SUPPORT] LPS-59425 Prevent bypassing domain validation

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Norbi,

I know we agreed to implement a full URL matching, but following that approach I faced multiple difficulties. The current approach, however, is simple and does the job well. First we remove protocol if present, then check if the url is protocol-relative to handle that case too.

I would hear your opinion happily. You can find me if you disagree with my approach. :)

By the way, moving removeProtocol to URLUtil according to our earlier discussion doesn't look good, because other remove* methods are all in HttpImpl. Furthermore, we should probably follow the deprecation process instead of simply removing from HttpImpl.

Thank you,
Pisti

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
Hi Norbi,

I have added improvements, including the ones you requested: regex compilation and unit test.

Thank you,

**Comment by istvansajtos** [comment]
ci:retest

**Comment by istvansajtos** [comment]
ci:retest

**Comment by lipusz** [comment]
Please, follow-up!

**Comment by NorbertKocsis** [comment]
Forwarded to https://github.com/topolik/liferay-portal/pull/270

Thanks!

**Pull request closed without merging**
