### PR TITLE
LPS-81573 Add test for .config format

### PR DESCRIPTION
**Pull request by csierra**
This pull add support for `.config` fileinstall format. 
To use it the files should end with `.config` suffix. 

Let me know if this addresses your problem for https://issues.liferay.com/browse/LPS-81573

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
Thanks! I will check it out.

**Comment by NorbertKocsis** [comment]
Hi,

Yes this works fine!

**Comment by NorbertKocsis** [comment]
Hi,

Do you need me to do anything else?

Br,
Norbert

**Comment by csierra** [comment]
oh... please just forward it to brian or some one from the core infra team

thx!

**Comment by csierra** [comment]
well...actually don't I will change some stuff and forward it

**Comment by NorbertKocsis** [comment]
Hi,

Thanks! I'm assigning the LPS to you then.

Br,
Norbert

**Pull request closed without merging**
